"""Export golden vectors + parameter headers for the three HLS designs.

Emits hw/golden/<design>/:
  params.h            weights/codebooks/indices/LUTs/requant constants
                      (HLS types from hw/hls/common/hw_config.h)
  golden.h            N=1000 stratified test vectors (inputs/outputs/labels)
  golden_inputs.npy   same data for Python-side checks (tests/test_hw_export)
  golden_outputs.npy, golden_labels.npy, golden_indices.npy
  manifest.json       shapes, scales, SHA256 of every artifact, emulator
                      accuracy on the FULL 10k test set (L1/L4 results)

CLI (one command per design = export + L1 + L4 gate):
  python -m funcodekan.hw.export --design d1|d2|d3 [--runs-dir runs_hw]
"""

from __future__ import annotations

import argparse
import hashlib
import json
from datetime import datetime, timezone
from pathlib import Path

import numpy as np
import torch

from funcodekan.data.mnist import get_mnist_loaders
from funcodekan.models.spline import DenseSplineKAN
from funcodekan.utils.training import set_seed

from . import fixed_point as fp
from .act_quant import QuantBranchKAN, rebuild_branch_model
from .hw_spec import (BASIS_FRAC_BITS, LOGIT_FRAC_BITS, QN, QP,
                      SILU_FRAC_BITS)
from .qat import QuantSplineKAN
from .verify import _collect_test_set, run_l1_fp32, run_l1_quant, run_l4

GOLDEN_N = 1000
PER_CLASS = 100


# ---------------------------------------------------------------------------
# helpers
# ---------------------------------------------------------------------------

def stratified_indices(labels: np.ndarray, per_class: int = PER_CLASS
                       ) -> np.ndarray:
    """First `per_class` occurrences of each class, in test-set order —
    deterministic, no RNG."""
    picks = []
    for c in range(10):
        idx = np.nonzero(labels == c)[0][:per_class]
        if len(idx) < per_class:
            raise ValueError(f"class {c} has only {len(idx)} test images")
        picks.append(idx)
    return np.sort(np.concatenate(picks))


def _fmt_int(v) -> str:
    return str(int(v))


def _fmt_f32(v) -> str:
    # .9g round-trips float32 exactly; ensure a valid C float literal
    # (".9g" renders whole numbers without a decimal point)
    s = format(float(np.float32(v)), ".9g")
    if "." not in s and "e" not in s and "n" not in s:
        s += ".0"
    return s + "f"


def c_array(name: str, ctype: str, arr: np.ndarray, fmt=_fmt_int,
            per_line: int = 16, dims: tuple | None = None) -> str:
    """Emit a const C array initializer. 1-D when dims is None; otherwise a
    2-D array with EXPLICIT nested braces (required for arrays of class type
    like ap_int<4>, where brace elision does not apply)."""
    flat = np.asarray(arr).reshape(-1)
    if dims is None:
        decl = f"[{len(flat)}]"
        body = []
        for i in range(0, len(flat), per_line):
            body.append(", ".join(fmt(v) for v in flat[i:i + per_line]))
        joined = ",\n  ".join(body)
        return f"static const {ctype} {name}{decl} = {{\n  {joined}\n}};\n"
    assert len(dims) == 2, "only 2-D arrays are emitted with dims"
    n_rows, n_cols = int(dims[0]), int(dims[1])
    assert n_rows * n_cols == len(flat), (name, dims, len(flat))
    a2 = np.asarray(arr).reshape(n_rows, n_cols)
    rows = []
    for r in range(n_rows):
        cells = []
        for i in range(0, n_cols, per_line):
            cells.append(", ".join(fmt(v) for v in a2[r, i:i + per_line]))
        rows.append("  {" + (",\n   ".join(cells)) + "}")
    joined = ",\n".join(rows)
    return (f"static const {ctype} {name}[{n_rows}][{n_cols}] = {{\n"
            f"{joined}\n}};\n")


def sha256_of(path: Path) -> str:
    h = hashlib.sha256()
    h.update(path.read_bytes())
    return h.hexdigest()


def _write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="ascii", newline="\n")


def _guard(name: str, body: str) -> str:
    g = f"FUNCODE_HW_{name.upper()}_H"
    # size checks run in csim/tb builds; the HLS synthesis front end is
    # pre-C++11 and does not know static_assert
    prelude = ("#ifndef HW_STATIC_ASSERT\n"
               "#ifdef __SYNTHESIS__\n"
               "#define HW_STATIC_ASSERT(cond, msg)\n"
               "#else\n"
               "#define HW_STATIC_ASSERT(cond, msg) static_assert(cond, msg)\n"
               "#endif\n"
               "#endif\n\n")
    return (f"// Auto-generated by funcodekan.hw.export -- DO NOT EDIT.\n"
            f"#ifndef {g}\n#define {g}\n\n{prelude}{body}\n#endif // {g}\n")


# ---------------------------------------------------------------------------
# params.h emitters
# ---------------------------------------------------------------------------

def _dims_block(model_layers) -> str:
    lines = [f"#define N_LAYERS {len(model_layers)}"]
    for l, layer in enumerate(model_layers):
        lines.append(f"#define L{l}_IN {layer.in_features}")
        lines.append(f"#define L{l}_OUT {layer.out_features}")
    lines.append("#define SPLINE_DIM 8")
    return "\n".join(lines) + "\n\n"


def _quant_layer_block(l: int, ql: fp.QuantLayer) -> str:
    parts = [
        c_array(f"l{l}_lut_b", "lut_t", ql.lut_b, dims=(16, 8)),
        c_array(f"l{l}_lut_s", "lut_t", ql.lut_s),
        f"static const mult_t l{l}_mult_spline = {ql.mult_spline};\n"
        f"static const mult_t l{l}_mult_base = {ql.mult_base};\n"
        f"static const int l{l}_shift = {ql.shift};\n",
    ]
    return "".join(parts)


def _fmt_hex32(v) -> str:
    return f"0x{int(v) & 0xFFFFFFFF:08x}u"


def pack_spline_words(spline_q: np.ndarray) -> np.ndarray:
    """[out,in,8] INT4 codes -> uint32 word per edge, nibble k at bits
    [4k+3:4k] (two's complement). Exactly 4 bits/weight — the ROM bit count
    equals the analytical W4 storage model."""
    q = spline_q.reshape(-1, 8).astype(np.int64) & 0xF
    words = np.zeros(len(q), dtype=np.uint64)
    for k in range(8):
        words |= (q[:, k].astype(np.uint64)) << (4 * k)
    return words.astype(np.uint32)


def pack_base_words(base_q: np.ndarray) -> np.ndarray:
    """[out,in] INT4 codes -> uint32 words grouping 8 consecutive outputs:
    word[(o>>3)*IN + i], nibble o&7. OUT padded to a multiple of 8 with
    zero nibbles (layer 2: OUT=10 -> 2 groups)."""
    out_f, in_f = base_q.shape
    groups = (out_f + 7) // 8
    words = np.zeros(groups * in_f, dtype=np.uint64)
    q = base_q.astype(np.int64) & 0xF
    for o in range(out_f):
        g, nib = o >> 3, o & 7
        words[g * in_f:(g + 1) * in_f] |= (q[o].astype(np.uint64)) << (4 * nib)
    return words.astype(np.uint32)


def emit_params_d2(model: fp.FixedPointModel, layers) -> str:
    # Weights are emitted NIBBLE-PACKED in POD uint32 words: the HLS 2019
    # front end (and the csim gcc) cannot digest ~450k ap_int initializers,
    # and packed words carry exactly 4 bits/weight so the BRAM accounting
    # stays equal to the analytical W4 model (docs/HW_FAIRNESS.md).
    body = _dims_block(layers)
    for l, ql in enumerate(model.layers):
        out_f, in_f = ql.base_q.shape
        groups = (out_f + 7) // 8
        body += f"#define L{l}_BASE_GROUPS {groups}\n"
        body += _quant_layer_block(l, ql)
        body += c_array(f"l{l}_spline_pk", "unsigned int",
                        pack_spline_words(ql.spline_q), fmt=_fmt_hex32,
                        per_line=8)
        body += c_array(f"l{l}_base_pk", "unsigned int",
                        pack_base_words(ql.base_q), fmt=_fmt_hex32,
                        per_line=8)
        body += (f"HW_STATIC_ASSERT(sizeof(l{l}_spline_pk)/"
                 f"sizeof(l{l}_spline_pk[0]) == L{l}_OUT*L{l}_IN, "
                 f"\"l{l}_spline_pk size\");\n")
        body += (f"HW_STATIC_ASSERT(sizeof(l{l}_base_pk)/"
                 f"sizeof(l{l}_base_pk[0]) == L{l}_BASE_GROUPS*L{l}_IN, "
                 f"\"l{l}_base_pk size\");\n")
    return _guard("params_d2", body)


def emit_params_d3(model: fp.FixedPointModel, layers) -> str:
    body = _dims_block(layers)
    for l, ql in enumerate(model.layers):
        ks = ql.spline_codebook_q.shape[0]
        kb = ql.base_codebook_q.shape[0]
        body += f"#define L{l}_KS {ks}\n#define L{l}_KB {kb}\n"
        body += _quant_layer_block(l, ql)
        body += c_array(f"l{l}_spline_codebook_q", "w4_t",
                        ql.spline_codebook_q, dims=(ks, 8))
        body += c_array(f"l{l}_base_codebook_q", "w4_t", ql.base_codebook_q)
        # *rom_t: POD in csim, narrow ap_uint under __SYNTHESIS__
        body += c_array(f"l{l}_spline_ids", "sidxrom_t", ql.spline_ids)
        body += c_array(f"l{l}_base_ids", "bidxrom_t", ql.base_ids)
        body += (f"HW_STATIC_ASSERT(sizeof(l{l}_spline_ids)/"
                 f"sizeof(l{l}_spline_ids[0]) == "
                 f"L{l}_OUT*L{l}_IN, \"l{l}_spline_ids size\");\n")
    return _guard("params_d3", body)


def emit_params_d1(model: fp.Fp32Model, layers) -> str:
    body = _dims_block(layers)
    body += "#define COEFF_DIM 9\n"
    for l, fl in enumerate(model.layers):
        out_f, in_f, cd = fl.weight.shape
        body += c_array(f"l{l}_weight", "float", fl.weight, fmt=_fmt_f32,
                        per_line=8, dims=(out_f * in_f, cd))
        # one grid row (all rows identical: same knots for every feature)
        body += c_array(f"l{l}_grid", "float", fl.grid[0], fmt=_fmt_f32)
        body += (f"HW_STATIC_ASSERT(sizeof(l{l}_weight)/sizeof(float) == "
                 f"L{l}_OUT*L{l}_IN*COEFF_DIM, \"l{l}_weight size\");\n")
    return _guard("params_d1", body)


def emit_golden(design: str, inputs: np.ndarray, outputs: np.ndarray,
                labels: np.ndarray) -> str:
    if design == "d1" or design.endswith("fp32"):
        in_t, out_t, in_fmt, out_fmt = "float", "float", _fmt_f32, _fmt_f32
    else:
        # POD types only: the csim gcc ICEs on large class-type initializers
        in_t, out_t, in_fmt, out_fmt = "in_code_t", "int", _fmt_int, _fmt_int
    body = (f"#define GOLDEN_N {len(inputs)}\n"
            f"#define GOLDEN_IN {inputs.shape[1]}\n"
            f"#define GOLDEN_OUT {outputs.shape[1]}\n\n")
    body += c_array("golden_inputs", in_t, inputs, fmt=in_fmt,
                    dims=inputs.shape)
    body += c_array("golden_outputs", out_t, outputs, fmt=out_fmt,
                    dims=outputs.shape)
    body += c_array("golden_labels", "unsigned char", labels)
    return _guard(f"golden_{design}", body)


# ---------------------------------------------------------------------------
# per-design export
# ---------------------------------------------------------------------------

def _finish_export(design: str, out_dir: Path, params_h: str, inputs, outputs,
                   labels, indices, manifest_extra: dict) -> dict:
    _write(out_dir / "params.h", params_h)
    _write(out_dir / "golden.h", emit_golden(design, inputs, outputs, labels))
    np.save(out_dir / "golden_inputs.npy", inputs)
    np.save(out_dir / "golden_outputs.npy", outputs)
    np.save(out_dir / "golden_labels.npy", labels)
    np.save(out_dir / "golden_indices.npy", indices)
    artifacts = ["params.h", "golden.h", "golden_inputs.npy",
                 "golden_outputs.npy", "golden_labels.npy",
                 "golden_indices.npy"]
    manifest = {
        "design": design,
        "generated": datetime.now(timezone.utc).isoformat(),
        "golden_n": int(len(inputs)),
        "stratification": f"first {PER_CLASS} test images per class",
        "sha256": {a: sha256_of(out_dir / a) for a in artifacts},
        **manifest_extra,
    }
    _write(out_dir / "manifest.json", json.dumps(manifest, indent=2))
    return manifest


def export_d1(dense: DenseSplineKAN, test_loader,
              out_dir=Path("hw/golden/fp32"),
              log_path="runs_hw/verification_log.json") -> dict:
    out_dir = Path(out_dir)
    np_model = fp.build_from_dense(dense)
    l1 = run_l1_fp32(dense, np_model, test_loader, log_path)
    x, y = _collect_test_set(test_loader)
    idx = stratified_indices(y)
    gin = x[idx].astype(np.float32)
    gout = np_model.forward(gin).astype(np.float32)
    manifest = _finish_export(
        "d1", out_dir, emit_params_d1(np_model, dense.layers),
        gin, gout, y[idx].astype(np.uint8), idx,
        {"l1": l1, "logit_tolerance_tb": 1e-3,
         "weight_shapes": [list(w.shape) for w in dense.weights]})
    return manifest


def _export_quant(design: str, wrapper, fp_model, test_loader, out_dir,
                  dense_fp32_acc: float | None, params_h: str,
                  extra: dict,
                  log_path="runs_hw/verification_log.json") -> dict:
    out_dir = Path(out_dir)
    l1 = run_l1_quant(f"{design}", wrapper, fp_model, test_loader, log_path)
    l4 = (run_l4(design, l1["emulator_acc"], dense_fp32_acc, log_path)
          if dense_fp32_acc is not None else None)
    x, y = _collect_test_set(test_loader)
    idx = stratified_indices(y)
    gin = fp_model.quantize_input(x[idx]).astype(np.int8)
    gout = fp_model.forward_codes(gin.astype(np.int64)).astype(np.int32)
    manifest = _finish_export(
        design, out_dir, params_h, gin, gout, y[idx].astype(np.uint8), idx,
        {"l1": l1, "l4": l4,
         "input_step": float(fp_model.input_step),
         "act_steps": wrapper.act_steps(),
         "basis_frac_bits": BASIS_FRAC_BITS,
         "silu_frac_bits": SILU_FRAC_BITS,
         "logit_frac_bits": LOGIT_FRAC_BITS,
         "int4_range": [QN, QP],
         "requant": [{"mult_spline": ql.mult_spline,
                      "mult_base": ql.mult_base, "shift": ql.shift}
                     for ql in fp_model.layers],
         **extra})
    return manifest


def export_d2(wrapper: QuantSplineKAN, test_loader,
              out_dir=Path("hw/golden/lsq_w4a4"),
              dense_fp32_acc: float | None = None,
              log_path="runs_hw/verification_log.json") -> dict:
    model = fp.build_from_d2(wrapper)
    scales = {f"layer{l}": {"spline_step": wrapper.int_weights(l)["spline_step"],
                            "base_step": wrapper.int_weights(l)["base_step"]}
              for l in range(len(wrapper.dense.layers))}
    return _export_quant("d2", wrapper, model, test_loader, out_dir,
                         dense_fp32_acc,
                         emit_params_d2(model, wrapper.dense.layers),
                         {"weight_steps": scales}, log_path)


def export_d3(wrapper: QuantBranchKAN, test_loader,
              out_dir=Path("hw/golden/funccode_w4a4"),
              dense_fp32_acc: float | None = None,
              log_path="runs_hw/verification_log.json") -> dict:
    model = fp.build_from_d3(wrapper)
    scales = {f"layer{l}": {"spline_step": wrapper.int_codebooks(l)["spline_step"],
                            "base_step": wrapper.int_codebooks(l)["base_step"]}
              for l in range(len(wrapper.branch.layers))}
    ks_kb = [{"Ks": int(ql.spline_codebook_q.shape[0]),
              "Kb": int(ql.base_codebook_q.shape[0])} for ql in model.layers]
    return _export_quant("d3", wrapper, model, test_loader, out_dir,
                         dense_fp32_acc,
                         emit_params_d3(model, wrapper.branch.layers),
                         {"codebook_steps": scales, "codebook_sizes": ks_kb},
                         log_path)


# ---------------------------------------------------------------------------
# checkpoint loading + CLI
# ---------------------------------------------------------------------------

def load_d2_wrapper(model_pt: Path, width=64, grid=5, order=3
                    ) -> QuantSplineKAN:
    ckpt = torch.load(model_pt, map_location="cpu", weights_only=True)
    wrapper = QuantSplineKAN(DenseSplineKAN(784, width, 10, grid, order))
    wrapper.load_state_dict(ckpt["state_dict"])
    return wrapper.eval()


def load_d3_wrapper(model_pt: Path, width=64, grid=5, order=3
                    ) -> QuantBranchKAN:
    ckpt = torch.load(model_pt, map_location="cpu", weights_only=True)
    branch = rebuild_branch_model(ckpt["clustered_export"], 784, width, 10,
                                  grid, order)
    wrapper = QuantBranchKAN(branch)
    wrapper.load_state_dict(ckpt["state_dict"])
    return wrapper.eval()


def _dense_fp32_acc(runs_dir: Path) -> float | None:
    summary = runs_dir / "branch_k32_s32_b16" / "summary.csv"
    if not summary.exists():
        return None
    import pandas as pd
    df = pd.read_csv(summary)
    row = df[df["stage"] == "dense_fp32"]
    return float(row["test_acc"].iloc[0]) if len(row) else None


def main(argv=None):
    p = argparse.ArgumentParser()
    p.add_argument("--design", required=True, choices=["d1", "d2", "d3"])
    p.add_argument("--runs-dir", type=str, default="runs_hw")
    p.add_argument("--out-root", type=str, default="hw/golden")
    p.add_argument("--seed", type=int, default=42)
    args = p.parse_args(argv)
    set_seed(args.seed)
    runs = Path(args.runs_dir)
    data = get_mnist_loaders(seed=args.seed, num_workers=0)
    dense_acc = _dense_fp32_acc(runs)
    if args.design == "d1":
        ckpt = torch.load(runs / "branch_k32_s32_b16" / "dense.pt",
                          map_location="cpu", weights_only=True)
        dense = DenseSplineKAN(784, 64, 10, 5, 3)
        dense.load_state_dict(ckpt["model"])
        m = export_d1(dense, data.test_loader,
                      Path(args.out_root) / "fp32")
    elif args.design == "d2":
        wrapper = load_d2_wrapper(runs / "d2_lsq_w4a4" / "model.pt")
        m = export_d2(wrapper, data.test_loader,
                      Path(args.out_root) / "lsq_w4a4", dense_acc)
    else:
        wrapper = load_d3_wrapper(runs / "d3_funccode_w4a4" / "model.pt")
        m = export_d3(wrapper, data.test_loader,
                      Path(args.out_root) / "funccode_w4a4", dense_acc)
    l1 = m.get("l1", {})
    print(f"[export] {args.design}: L1 passed={l1.get('passed')} "
          f"emulator_acc={l1.get('emulator_acc', l1.get('numpy_acc'))}")
    if not l1.get("passed"):
        raise SystemExit(f"L1 FAILED for {args.design} — see verification log")


if __name__ == "__main__":
    main()
